### ISSUE TITLE
Similarities to "npm view"?

### ISSUE THREAD

**Issue by lewiscowper** [bahmutov/json-package#1]
Judging only by the readme and your blog post about tools that you use, there's a built in npm command to do what this module does as far as I can tell, called `view`, and run with `npm view [package] [field]`.

[More info and docs here](https://docs.npmjs.com/cli/view)

**Comment by bahmutov** [comment]
Yup, agree, but there are differences:
- local package lookup without name (faster)
- json-package works with prefix (again faster)
